/* -------- données regroupées par formule -------- */
const minerals = [
  { name: ["Argent natif", "Argent"], formula: "Ag", system: ["cubique"] },
  { name: ["Or natif", "Or"], formula: "Au", system: ["cubique"] },
  { name: ["Fer natif", "Fer"], formula: "Fe", system: ["cubique"] },
  { name: ["Diamant"], formula: "C", system: ["cubique"] },
  { name: ["Graphite"], formula: "C", system: ["hexagonal"] },
  { name: ["Stannite"], formula: "Cu2FeSnS4", system: ["tétragonal"] },
  { name: ["Wurtzite"], formula: "(Zn,Fe)S", system: ["hexagonal"] },
  { name: ["Pentlandite"], formula: "(Fe,Ni)9S8", system: ["cubique"] },
  { name: ["Löllingite"], formula: "FeAs2", system: ["orthorhombique"] },
  { name: ["Skutterudite"], formula: "(Co,Ni)As3−x", system: ["cubique"] },
  { name: ["Pyrargyrite"], formula: "Ag3SbS3", system: ["trigonal"] },
  { name: ["Proustite"], formula: "Ag3AsS3", system: ["trigonal"] },
  { name: ["Enargite"], formula: "Cu3AsS4", system: ["orthorhombique"] },
  { name: ["Anatase"], formula: "TiO2", system: ["tétragonal"] },
  { name: ["Brookite"], formula: "TiO2", system: ["orthorhombique"] },
  { name: ["Spinelle"], formula: "MgAl2O4", system: ["cubique"] },
  { name: ["Chrysoberyl"], formula: "Be(AlO2)2", system: ["orthorhombique"] },
  { name: ["Perovskite"], formula: "CaTiO3", system: ["orthorhombique"] },
  { name: ["Brucite"], formula: "Mg(OH)2", system: ["trigonal"] },
  { name: ["Manganite"], formula: "MnO(OH)", system: ["monoclinique"] },
  { name: ["Gibbsite"], formula: "Al(OH)3", system: ["monoclinique"] },
  { name: ["Sylvite"], formula: "KCl", system: ["cubique"] },
  { name: ["Atacamite"], formula: "CuCl2(OH)3", system: ["orthorhombique"] },
  { name: ["Magnesite"], formula: "MgCO3", system: ["trigonal"] },
  { name: ["Nitronatrite"], formula: "NaNO3", system: ["trigonal"] },
  { name: ["Nitre"], formula: "KNO3", system: ["orthorhombique"] },
  { name: ["Crocoïte"], formula: "PbCrO4", system: ["monoclinique"] },
  { name: ["Scheelite"], formula: "CaWO4", system: ["tétragonal"] },
  { name: ["Wulfénite"], formula: "PbMoO4", system: ["tétragonal"] },
  { name: ["Xénotime"], formula: "YPO4", system: ["tétragonal"] },
  { name: ["Monazite"], formula: "(Ce,La,Ne,Th)PO4", system: ["monoclinique"] },
  { name: ["Mimétite"], formula: "Pb5(AsO4)3Cl", system: ["hexagonal"] },
  { name: ["Vanadinite"], formula: "Pb5(VO4)3Cl", system: ["hexagonal"] },
  { name: ["Pyrope"], formula: "Mg3Al2[SiO4]3", system: ["cubique"] },
  { name: ["Almandin"], formula: "Fe2+3Al2[SiO4]3", system: ["cubique"] },
  { name: ["Spessartine"], formula: "Mn3Al2[SiO4]3", system: ["cubique"] },
  { name: ["Grossulaire"], formula: "Ca3Al2[SiO4]3", system: ["cubique"] },
  { name: ["Andradite"], formula: "Ca3Fe2[SiO4]3", system: ["cubique"] },
  { name: ["Uvarovite"], formula: "Ca3Cr2[SiO4]3", system: ["cubique"] },
  { name: ["Titanite"], formula: "CaTiSiO5", system: ["monoclinique"] },
  { name: ["Ottrelite"], formula: "(Mn2+,Fe2+,Mg)Al2[SiO4]O(OH)2", system: ["monoclinique"] },
  { name: ["Hémimorphite"], formula: "Zn4Si2O7(OH)2·(H2O)", system: ["orthorhombique"] },
  { name: ["Diopside"], formula: "CaMg[Si2O6]", system: ["monoclinique"] },
  { name: ["Enstatite"], formula: "Mg2[Si2O6]", system: ["orthorhombique"] },
  { name: ["Trémolite"], formula: "Ca2Mg5[Si4O11(OH,F)]2", system: ["monoclinique"] },
  { name: ["Wollastonite"], formula: "CaSiO3", system: ["triclinique"] },
  { name: ["Phlogopite"], formula: "KMg3[Si3AlO10](OH)2", system: ["monoclinique"] },
  { name: ["Tridymite"], formula: "SiO2", system: ["triclinique"] },
  { name: ["Cristobalite"], formula: "SiO2", system: ["tétragonal"] },
  { name: ["Nepheline"], formula: "Na3K[Al4Si4O16]", system: ["hexagonal"] },
  { name: ["Orthose"], formula: "K[AlSi3O8]", system: ["triclinique", "orthorhombique"] },
  { name: ["Serpentine"], formula: "Mg6[Si4O10](OH)8", system: ["monoclinique", "orthorhombique"] },
  { name: ["Pyrrhotite"], formula: "Fe1−xS", system: ["monoclinique", "hexagonal"] },
  { name: ["Chloritoïde"], formula: "FeAl2O[SiO4](OH)2", system: ["monoclinique", "tétragonal"] },
  { name: ["Anorthite"], formula: "Ca[Al2Si2O8]", system: ["triclinique"] },
  { name: ["Albite"], formula: "Na[AlSi3O8]", system: ["triclinique"] },
  { name: ["Cuivre natif"], formula: "Cu", system: ["cubique"] },
  { name: ["Soufre natif"], formula: "S", system: ["orthorhombique"] },
  { name: ["Chalcocite"], formula: "Cu2S", system: ["monoclinique"] },
  { name: ["Bornite"], formula: "Cu5FeS4", system: ["orthorhombique"] },
  { name: ["Galène"], formula: "PbS", system: ["cubique"] },
  { name: ["Sphalérite"], formula: "(Zn,Fe)S", system: ["cubique"] },
  { name: ["Chalcopyrite"], formula: "CuFeS2", system: ["tétragonal"] },
  { name: ["Sodalite"], formula: "Na8[Al6Si6O24]Cl2", system: ["cubique"] }
];